branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "mypy"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      allow_deletions: false
      allow_force_pushes: false
