repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        args: [check]
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        args: [aegis/modules, aegis/core/ini_parser.py]
