[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"

[tool.mypy]
python_version = "3.11"
files = ["aegis/modules", "aegis/core"]
ignore_missing_imports = true
